variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  image: $CI_REGISTRY/psyco/gdart/development:21.2.0
  script:
    - git rev-parse --short HEAD > version.txt
    - git submodule update --init --recursive
    - pip3 install pyyaml
    - ./compile-all.sh
    - ./run-gwit.sh --witness examples/witnesses/spec1-5_product56.yml/witness.GraphML examples/benchmarks/spec1-5_product56.yml
    - ./run-gwit.sh --witness examples/witnesses/assert2.yml/witness.GraphML examples/benchmarks/assert2.yml 
    - ./run-gwit.sh --witness examples/witnesses/Ackermann01.yml/witness.GraphML  examples/benchmarks/Ackermann01.yml
  artifacts:
    name: "gwit"
    paths:
        - version.txt
        - run-gwit.sh
        - weave-witness.py
        - executor.sh
        - README.md
        - LICENSE
        - dse/README.md
        - dse/LICENSE
        - spout/README.md
        - spout/LICENSE
        - ./spout/sdk/mxbuild/linux-amd64/GRAALVM_ESPRESSO_NATIVE_CE_JAVA11/graalvm-espresso-native-ce-java11-21.2.0/
        - verifier-stub/README.md
        - verifier-stub/LICENSE
        - ./dse/target/dse-0.0.1-SNAPSHOT-jar-with-dependencies.jar
        - ./verifier-stub/target/verifier-stub-1.0.jar
