variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  image: $CI_REGISTRY/psyco/gdart/development:21.2.0
  script:
    - git rev-parse --short HEAD > version.txt
    - git submodule update --init --recursive
    - pip3 install pyyaml
    - ./compile-all.sh
    - ./run-gwit.sh --witness examples/witnesses/spec1-5_product56.yml/witness.GraphML examples/benchmarks/spec1-5_product56.yml
    - ./run-gwit.sh --witness examples/witnesses/assert2.yml/witness.GraphML examples/benchmarks/assert2.yml 
    - ./run-gwit.sh --witness examples/witnesses/Ackermann01.yml/witness.GraphML  examples/benchmarks/Ackermann01.yml
    - mkdir -p val_gwit/dse/target
    - mv version.txt val_gwit
    - mv run-gwit.sh val_gwit
    - mv weave-witness.py val_gwit
    - mv executor.sh val_gwit
    - mv README.md val_gwit
    - mv LICENSE val_gwit
    - mv dse/README.md val_gwit/dse/
    - mv dse/LICENSE val_gwit/dse/LICENSE
    - mkdir -p val_gwit/spout
    - mv spout/README.md val_gwit/spout/ 
    - mv spout/LICENSE val_gwit/spout/
    - mkdir -p val_gwit/spout/sdk/mxbuild/linux-amd64/GRAALVM_ESPRESSO_NATIVE_CE_JAVA11/graalvm-espresso-native-ce-java11-21.2.0/
    - mv spout/sdk/mxbuild/linux-amd64/GRAALVM_ESPRESSO_NATIVE_CE_JAVA11/graalvm-espresso-native-ce-java11-21.2.0/* val_gwit/spout/sdk/mxbuild/linux-amd64/GRAALVM_ESPRESSO_NATIVE_CE_JAVA11/graalvm-espresso-native-ce-java11-21.2.0/
    - mkdir -p val_gwit/verifier-stub/target
    - mv verifier-stub/README.md val_gwit/verifier-stub/
    - mv verifier-stub/LICENSE val_gwit/verifier-stub/
    - mv ./dse/target/dse-0.0.1-SNAPSHOT-jar-with-dependencies.jar val_gwit/dse/target/dse-0.0.1-SNAPSHOT-jar-with-dependencies.jar
    - mv ./verifier-stub/target/verifier-stub-1.0.jar val_gwit/verifier-stub/target/verifier-stub-1.0.jar
  artifacts:
    name: "val_gwit"
    paths:
        - val_gwit
